# Generated by Django 4.1.7 on 2023-05-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordered_item",
            old_name="notice",
            new_name="ghichu",
        ),
    ]
