# Generated by Django 4.1.7 on 2023-05-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_notice_ordered_item_ghichu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordered_item",
            old_name="ghichu",
            new_name="notice",
        ),
    ]
