# Generated by Django 4.1.7 on 2023-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_ghichu_ordered_item_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordered_item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordered_item',
            name='price_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('comming soon', 'comming soon')], default='có sẵn', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MILK TEA', 'MILK TEA'), ('SODA', 'SODA'), ('FRESH MILK', 'FRESH MILK'), ('FRUIT TEA', 'FRUIT TEA'), ('JUNK FOOD', 'JUNK FOOD'), ('OTHER DRINK', 'OTHER DRINK')], default='TRÀ SỮA', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_long',
            field=models.TextField(default='có sẵn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.CharField(default='có sẵn', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=50000),
        ),
    ]
