# Generated by Django 3.2.9 on 2023-05-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_id_alter_ordered_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đã chuẩn bị', 'Đã chuẩn bị'), ('Đang giao', 'Đang giao'), ('Đã giao', 'Đã giao')], default='Chờ xác nhận', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordered_item',
            name='price_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('có sẵn', 'có sẵn'), ('không có sẵn', 'không có sẵn'), ('sắp ra mắt', 'sắp ra mắt')], default='có sẵn', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TRÀ SỮA', 'TRÀ SỮA'), ('SODA', 'SODA'), ('SỮA TƯƠI', 'SỮA TƯƠI'), ('TRÀ TRÁI CÂY', 'TRÀ TRÁI CÂY'), ('ĐỒ ĂN VẶT', 'ĐỒ ĂN VẶT'), ('THỨC UỐNG KHÁC', 'THỨC UỐNG KHÁC')], default='TRÀ SỮA', max_length=32),
        ),
    ]
