# Generated by Django 4.1.7 on 2023-05-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_status_alter_order_total_price_and_more"),
        ("orders", "0005_auto_20230518_2137"),
    ]

    operations = []
